x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  proxy:
    image: docker.io/library/nginx 
    ports:
      # Note, change lemmy_port in vars.yml if it is already in use on your system
      - "127.0.0.1:{{ lemmy_port }}:8536"
    volumes:
      - ./nginx_internal.conf:/etc/nginx/nginx.conf:ro,Z
      - ./proxy_params:/etc/nginx/proxy_params:ro,Z
    restart: always
    logging: *default-logging
    depends_on:
      - pictrs
      - lemmy-ui

  lemmy:
    image: {{ lemmy_docker_image }}
    hostname: lemmy
    restart: always
    logging: *default-logging
    environment:
{% if lemmy_env_vars is defined and lemmy_env_vars|length > 0 %}
{% for item in lemmy_env_vars %}
{% for key, value in item.items() %}
      - {{ key }}={{ value }}
{% endfor %}
{% endfor %}
{% endif %}
    volumes:
      - ./lemmy.hjson:/config/config.hjson:Z
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: {{ lemmy_docker_ui_image }}
    environment:
{% if lemmyui_env_vars is defined and lemmyui_env_vars|length > 0 %}
{% for item in lemmyui_env_vars %}
{% for key, value in item.items() %}
      - {{ key }}={{ value }}
{% endfor %}
{% endfor %}
{% endif %}
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes:Z
    depends_on:
      - lemmy
    restart: always
    logging: *default-logging

  pictrs:
    image: docker.io/asonix/pictrs:0.5
    # this needs to match the pictrs url in lemmy.hjson
    hostname: pictrs
    # we can set options to pictrs like this, here we set max. image size and forced format for conversion
    # entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt -m 4 --image-format webp
    environment:
{% if pictrs_env_vars is defined and pictrs_env_vars|length > 0 %}
{% for item in pictrs_env_vars %}
{% for key, value in item.items() %}
      - {{ key }}={{ value }}
{% endfor %}
{% endfor %}
{% endif %}
{% if pictrs_safety is defined and pictrs_safety|bool == true %}
      - PICTRS__MEDIA__EXTERNAL_VALIDATION=http://{{ domain }}:14051/api/v1/scan/IPADDR
{% endif %}
    user: 991:991
    restart: always
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 4gb
    depends_on:
      - postgres

  postgres:
    image: docker.io/pgautoupgrade/pgautoupgrade:16-alpine
    hostname: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
{% if postgres_env_vars is defined and postgres_env_vars|length > 0 %}
{% for item in postgres_env_vars %}
{% for key, value in item.items() %}
      - {{ key }}={{ value }}
{% endfor %}
{% endfor %}
{% endif %}
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:Z
      - ./customPostgresql.conf:/etc/postgresql.conf:Z
    restart: always
    command: postgres -c config_file=/etc/postgresql.conf
    shm_size: {{ postgres_shm }}
    logging: *default-logging

{% if pictrs_safety is defined and pictrs_safety|bool == true %}
  pictrs-safety:
    image: ghcr.io/db0/pictrs-safety:v1.2.2
    hostname: pictrs-safety
    environment:
{% if pictrs_safety_env_vars is defined and pictrs_safety_env_vars|length > 0 %}
{% for item in pictrs_safety_env_vars %}
{% for key, value in item.items() %}
      - {{ key }}={{ value }}
{% endfor %}
{% endfor %}
{% endif %}
    ports:
      - "127.0.0.1:14051:14051"
    user: 991:991
    restart: always
    logging: *default-logging
    depends_on:
      - pictrs
{% endif %}

  watchtower_apps:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=1600
    restart: always
  voyager:
    image: ghcr.io/aeharding/voyager:main
    ports:
      - "127.0.0.1:5314:5314"
    environment:
      - CUSTOM_LEMMY_SERVERS={{ domain }}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
  photon:
    image: ghcr.io/xyphyn/photon
    ports:
      - "127.0.0.1:5315:3000"
    environment:
      - PUBLIC_INSTANCE_URL={{ domain }}
      - PUBLIC_NSFW_BLUR=false
      - PUBLIC_SHOW_INSTANCES_USER=false
      - PUBLIC_SHOW_INSTANCES_COMMUNITY=false
      - PUBLIC_SHOW_INSTANCES_COMMENTS=false
      - PUBLIC_EXPAND_SIDEBAR=false
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
  alexandrite:
    image: ghcr.io/sheodox/alexandrite
    ports:
      - "127.0.0.1:5316:3000"
    environment:
      - ALEXANDRITE_DEFAULT_INSTANCE={{ domain }}
      - ALEXANDRITE_FORCE_INSTANCE={{ domain }}
      - ALEXANDRITE_WELCOME_INSTANCE_HELP=false
      - ALEXANDRITE_WELCOME_LEMMY_HELP=false
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
  mlmym:
    image: ghcr.io/rystaf/mlmym:latest
    environment:
      - LEMMY_DOMAIN={{ domain }}
    ports:
      - 127.0.0.1:5319:8080
    restart: always
  tesseract:
    image: ghcr.io/asimons04/tesseract:v1.4.21
    environment:
      # The domain of Tesseract's 'default' instance. This is the only required config variable
      - PUBLIC_INSTANCE_URL={{ domain }}
      # By default, Tesseract locks itself to the configured instance. To allow users to add accounts from other instances, set this to false.
      - PUBLIC_LOCK_TO_INSTANCE=true
      # Feed, feed sort, and comment sort settings
      - PUBLIC_DEFAULT_FEED=Local
      - PUBLIC_DEFAULT_FEED_SORT=Active
      - PUBLIC_DEFAULT_COMMENT_SORT=Top
      # Default to Dark Theme instead of "System"
      - PUBLIC_THEME=dark
      # Media Proxying
      # Enable the media proxying module and make it available for use.  It is disabled by default.
      - PUBLIC_ENABLE_MEDIA_PROXY=true
      # List of domains that should not be proxied (content reasons, because they won't work with the proxy, etc)
      - PUBLIC_MEDIA_PROXY_BLACKLIST=mintboard.org,iili.io,img.shields.io
      - PUBLIC_ENABLE_MEDIA_PROXY_LOCAL=true
      # Pre-set the "Use media proxy" setting for all users.  If set to false (default), users will need to go into Settings->Media to enable image proxying.
      - PUBLIC_ENABLE_USER_MEDIA_PROXY=true
      # Media Caching; disabled by default. Enabled and configured here.
      - PUBLIC_ENABLE_MEDIA_CACHE=true
      - PUBLIC_ENABLE_MEDIA_CACHE_LOCAL=true
      - PUBLIC_MEDIA_CACHE_DURATION=4320
      - PUBLIC_MEDIA_CACHE_KEEP_HOT_ITEMS=true
      - PUBLIC_MEDIA_CACHE_MAX_SIZE=500
      - PUBLIC_MEDIA_CACHE_HOUSEKEEP_INTERVAL=5
      - PUBLIC_MEDIA_CACHE_HOUSEKEEP_STARTUP=true
      # List of Invidious/Piped domains which should be used for detection. See docs/CustomYoutubeFrontends.md for more in fo.
      - |-
        PUBLIC_CUSTOM_INVIDIOUS=
          i.devol.it,
          piped.adminforge.de
    # Tesseract uses /app/cache inside the container to persist lookups and for the media cache. This will work without a volume, but anything cached will not persist after the container is restarted.
    # Note:  The host directory must be owned by UID/GID 1000.
    volumes:
      - ./volumes/tesseract/cache:/app/cache
    # Bind to localhost:8081 instead of the container's default port of 3000
    ports:
      - 127.0.0.1:5320:3000
    restart: "always"